#
# rkralik@fnal.gov
#

PACKAGE := NuMagMomentAna
SUBDIRS := Analysis Cuts Vars OscCalc Systs Prediction

########################################################################
include SoftRelTools/standard.mk
